CREATE TABLE news_lists (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	title VARCHAR(255) NOT NULL,
	category VARCHAR(50) NOT NULL,
	date VARCHAR(50) NOT NULL,
	url VARCHAR(255),
	content LONGTEXT NOT NULL,
	
	PRIMARY KEY (id)
);